config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'donation/new'
  get 'donation/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'categories#index' # mainpage. The Rails router maps the root route to the index action of CategoriesController
  resources :categories do
    resources :articles do
      resources :comments
    end
  end 

  resources :donations, only: [:new, :create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
    include Visible
  
    has_many :comments, dependent: :destroy
    belongs_to :category
  
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
  end

app/models/category.rb
class Category < ApplicationRecord
    has_many :articles, dependent: :destroy
  
    validates :name, presence: true, uniqueness: true
  end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include Visible

  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end
  
    class_methods do
      def public_count
        where(status: 'public').count
      end
    end
  
    def archived?
      status == 'archived'
    end
  end
  

app/models/donation.rb
class Donation < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_category
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with name: "Hod", password: "secret", except: [:index, :show]

  def index
    @articles = @category.articles
  end

  def show
    # @article = Article.find(params[:id])
  end

  def new
    # @article = Article.new
    @article = @category.articles.build
  end

  def create
    # @article = Article.new(article_params)

    # if @article.save
    #   redirect_to @article
    # else
    #   render :new, status: :unprocessable_entity
    # end
    @article = @category.articles.build(article_params)
    if @article.save
      redirect_to category_article_path(@category, @article), notice: 'Article was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # @article = Article.find(params[:id])
  end

  def update
    # @article = Article.find(params[:id])

    # if @article.update(article_params)
    #   redirect_to @article
    # else
    #   render :edit, status: :unprocessable_entity
    # end
    # @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to category_article_path(@category, @article), notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    # @article = Article.find(params[:id])
    # redirect_to root_path, status: :see_other

    @article.destroy
    redirect_to category_articles_path(@category), notice: 'Article was successfully destroyed.'    
  end

  private

  def set_category
    @category = Category.find(params[:category_id])
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :status)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: %i[edit show update destroy]
    http_basic_authenticate_with name: 'hod', password: 'secret', except: %i[index]
    def index
      @categories = Category.all
    end
  
    def show
    end
  
    def new
      @category = Category.new
    end
  
    def create
      @category = Category.new(categories_params)
  
      if @category.save
        redirect_to category_articles_path(@category), notice: 'Category was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def edit
      # @category
    end
  
    def update
      if @category.update(categories_params)
        redirect_to root_path, notice: 'Category was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @category.destroy
      redirect_to root_path, notice: 'Article was successfully destroyed.'
    end
  
    # def article_count
    #   articles.count
    # end
  
    private
  
    def set_category
      @category = Category.find(params[:id])
    end
  
    def categories_params
      params.require(:category).permit(:name, :description)
    end
  end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
    http_basic_authenticate_with name: "Hod", password: "secret", only: :destroy
    
    def index 
      @comments = Comment.where(article_id: params[article_id])
      render json: @comments 
    end
      def create
        @category = Category.find(params[:category_id])
        @article = Article.find(params[:article_id])
    
        @comment = @article.comments.create(comment_params)
    
        redirect_to category_article_path(@category, @article)
      end
    
      def destroy
        @category = Category.find(params[:category_id])
        @article = Article.find(params[:article_id])
    
        @comment = @article.comments.find(params[:id])
        
        @comment.destroy
        redirect_to category_article_path(@category, @article), status: :see_other
      end
    
      private
    
      def comment_params
        params.require(:comment).permit(:commenter, :body, :status)
      end
    end
  

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  def new
    @donation = Donation.new
  end
  def create
    @donation = Donation.new(donation_params)
    #charge the user's card
  charge = Stripe::Charge.create({
    amount: @donation.amount * 100, #convert to cents
    currency: 'usd',
    source: params[:stripe_token],
    description: 'Donation',
  })
  @donation.save
  flash[:success] = 'Thank you for your donation!'
    redirect_to root_path
  rescue Stripe::CardError => e
    flash[:error] = e.message
    render :new
  end
  private
  def donation_params
    params.require(:donation).permit(:first_name, :last_name, :email, :amount)
end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/donation_helper.rb
module DonationHelper
end

app/helpers/donations_helper.rb
module DonationHelper
end

app/views/articles/_form.html.erb
<%= form_with model: [@category] do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <% category.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :description %><br>
      <%= form.text_area :description %><br>
      <% category.errors.full_messages_for(:des).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

Our blog has <%= Article.public_count %> articles and counting!

<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title, category_article_path(article.category, article) %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "New Article", new_category_article_path(@category) %>
<br>
<%= link_to "Edit Category", edit_category_path(@category) %>
<br>
<%= link_to "Delete Category", category_path(@category), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>
<p><strong>Category:</strong> <%= @article.category.name %></p>
<ul>
  <li><%= link_to "Edit", edit_category_article_path(@category, @article) %></li>
  <li><%= link_to "Delete", category_article_path(@category), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>
</ul>

<div class="comment-section"
<h2>Comments</h2>
<div id="category-id" data-category="<% @category.id %>"
<button id="load-comments"> load-comments</button>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

  
 

app/views/categories/index.html.erb
<h1>Categories</h1>
<ul>
  <% @categories.each do |category| %>
    <li class = "container"><strong><%= link_to category.name, category_articles_path(category) %></strong>:  
    <% count = category.articles.count %> 
    <%= "#{count} #{count > 1 ? 'articles' : 'article'}" %>
    <br> <em> <%= category.description %> </em></li>
  <% end %>
</ul>

<%= link_to "New Category", new_category_path(@category) %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to "Delete Comment", category_article_comment_path(@category, @article, comment), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
    } %>
  </p>
  <button id="like">Like Comment</button>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @category, @article, @article.comments.build ] do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body, id: 'comment-body' %>
    </p>

    <p>
        <%= form.label :status %><br>
        <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
  

app/views/donation/new.html.erb
<h1>Make a Donation</h1>

<%= form_with(model: @donation, url: donations_path, method: 'post', local: true, id: 'donation-form') do |form| %>

    
  <div class="field">
    #first name already exists
    <%= form.label :first_name %>
    <%= form.text_area :first_name %>
  </div>
   #last name already exists
  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_area :last_name %>
  </div>

    # New fields for email and amount 
  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, class: 'form-control' %>
  </div>

  <!-- Card and error divs wrapped in card-container -->
  <div id="card-container">
    <div id="card-element" class="form-control"></div>
    <div id="card-errors" role="alert"></div>
  </div>

  <button id="donate-button" class="btn btn-primary">Donate</button>
<% end %>

app/views/donations/create.html.erb
<h1>Donation#create</h1>
<p>Find me in app/views/donation/create.html.erb</p>

app/views/donations/new.html.erb
<h1>Make a Donation</h1>

<%= form_with(model: @donation, url: donations_path, method: 'post', local: true, id: 'donation-form') do |form| %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>
  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div> 
  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, class: 'form-control' %>
  </div>

  
  <div id="card-container">
    <div id="card-element" class="form-control"></div>
    <div id="card-errors" role="alert"></div>
  </div>

  <button id="donate-button" class="btn btn-primary">Donate</button>
<% end %>

app/views/layouts/applications.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %> 
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'style.css' %>
    <%= stylesheet_link_tag 'donations.css' %>

    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>
    <%= javascript_include_tag 'https://js.stripe.com/v3/' %>
    <%= javascript_pack_tag "application" %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>